DROP TABLE IF EXISTS Request;
DROP TABLE IF EXISTS User;

DROP TABLE IF EXISTS Photo;
DROP TABLE IF EXISTS BirthCertificate;
DROP TABLE IF EXISTS NoticeOfAdmission;
DROP TABLE IF EXISTS Usepat;
DROP TABLE IF EXISTS GoodMoral;
DROP TABLE IF EXISTS Form138;
DROP TABLE IF EXISTS PersonalDataSheet;
DROP TABLE IF EXISTS DataPrivacyProvision;
DROP TABLE IF EXISTS HonorableDismissal;
DROP TABLE IF EXISTS MarriageCertificate;
DROP TABLE IF EXISTS PromissoryNote;
DROP TABLE IF EXISTS HealthStateDeclaration;
DROP TABLE IF EXISTS MedicalCertificate;
DROP TABLE IF EXISTS Form137;
DROP TABLE IF EXISTS ApprovalSheet;
DROP TABLE IF EXISTS ApplicationForGraduation;
DROP TABLE IF EXISTS ShiftersForm;
DROP TABLE IF EXISTS CertificateOfLowIncome;
DROP TABLE IF EXISTS TOR;
DROP TABLE IF EXISTS NMAT;
DROP TABLE IF EXISTS Indigency;
DROP TABLE IF EXISTS Clearance;
DROP TABLE IF EXISTS LeaveOfAbsence;
DROP TABLE IF EXISTS AdvancedCreditForm;
DROP TABLE IF EXISTS IncompleteForm;
DROP TABLE IF EXISTS SubjectValidationForm;
DROP TABLE IF EXISTS Substitution;
DROP TABLE IF EXISTS AffidavitOfUndertaking;
DROP TABLE IF EXISTS Other;

DROP TABLE IF EXISTS Student;

DROP TABLE IF EXISTS Major;
DROP TABLE IF EXISTS Program;
