services: 
  db: 
    image: mysql
    container_name: dev-db
    restart: on-failure
    env_file:
      - "./.db.env"
    ports:
      - "3306:3306"
    volumes:
      - "./db/migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/init.sql"
