// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DefaultLayout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>OUR-SRTS</title><link rel=\"icon\" type=\"image/x-icon\" href=\"/assets/images/logo.png\"><link rel=\"stylesheet\" href=\"/assets/styles/style.css\"><!-- Alpine Core --><script defer src=\"/assets/scripts/alpine_core.js\"></script><!-- Alpine Plugins --><script defer src=\"/assets/scripts/alpine_focus.js\"></script><script defer src=\"/assets/scripts/alpine_collapse.js\"></script></head><body class=\"font-roboto text-sm\"><header><div class=\"max-h-[4rem] border-0 border-b-[1px] border-gray-400\"><div class=\"h-2 bg-red-900\"></div><div class=\"flex items-center justify-between px-2\"><div class=\"flex gap-4 p-2\"><div class=\"aspect-square w-10\"><img src=\"/assets/images/logo.png\" alt=\"registrar logo\"></div><div class=\"text-sm text-primary\"><p>Tagum -</p><p>Mabini</p></div><div class=\"inline-block min-h-[1em] w-1 self-stretch bg-yellow-400 \"></div><div class=\"text-sm\"><p>Office of the University Registrar</p><p><span class=\"text-primary\">Student Records</span> <span class=\"text-yellow-500\">Tracking System</span></p></div></div></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"absolute right-0 bottom-4 left-0 text-center\"><p class=\"text-xs text-gray-500\">Office of the University Registrar © 2023</p></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
